/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // SLF4J API for logging
    implementation("org.slf4j:slf4j-api:2.0.12")
    
    // Logback for SLF4J implementation
    implementation("ch.qos.logback:logback-classic:1.5.3")

    // MySQL Connector dependency
    implementation("mysql:mysql-connector-java:8.0.33")

    // H2 Database for testing
    testImplementation("com.h2database:h2:2.2.224")

    // Flyway for database migrations
    implementation("org.flywaydb:flyway-core:12.3.0")
    implementation("org.flywaydb:flyway-mysql:12.3.0")

    // JPA API for entity management
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
    
    // Hibernate as JPA implementation
    implementation("org.hibernate.orm:hibernate-core:6.4.4.Final")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "task.management.App"
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "task.management.App"
    }
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier.set("all")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


