/*
 * This source file was generated by the Gradle 'init' task
 */
package task.management;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test
    @DisplayName("App should have a greeting")
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assertEquals("Task Management Board System v3.0", classUnderTest.getGreeting());
    }
    
    @Test
    @DisplayName("App greeting should mention Task Management")
    void appGreetingShouldMentionTaskManagement() {
        App app = new App();
        String greeting = app.getGreeting();
        
        assertTrue(greeting.contains("Task Management"), 
            "Greeting should mention Task Management");
    }
}
